# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import compute_pb2 as compute__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in compute_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CoordinatorStub(object):
    """Coordinator service (lightweight directory)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterNode = channel.unary_unary(
                '/Coordinator/RegisterNode',
                request_serializer=compute__pb2.NodeRegistration.SerializeToString,
                response_deserializer=compute__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.GetAvailableNodes = channel.unary_unary(
                '/Coordinator/GetAvailableNodes',
                request_serializer=compute__pb2.NodeRequest.SerializeToString,
                response_deserializer=compute__pb2.NodeListResponse.FromString,
                _registered_method=True)
        self.UpdateNodeStatus = channel.unary_unary(
                '/Coordinator/UpdateNodeStatus',
                request_serializer=compute__pb2.NodeStatus.SerializeToString,
                response_deserializer=compute__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.RegisterTaskReplica = channel.unary_unary(
                '/Coordinator/RegisterTaskReplica',
                request_serializer=compute__pb2.TaskReplicaRequest.SerializeToString,
                response_deserializer=compute__pb2.TaskReplicaResponse.FromString,
                _registered_method=True)
        self.GetBackupForTask = channel.unary_unary(
                '/Coordinator/GetBackupForTask',
                request_serializer=compute__pb2.TaskBackupRequest.SerializeToString,
                response_deserializer=compute__pb2.TaskBackupResponse.FromString,
                _registered_method=True)
        self.PromoteBackupToPrimary = channel.unary_unary(
                '/Coordinator/PromoteBackupToPrimary',
                request_serializer=compute__pb2.PromotionRequest.SerializeToString,
                response_deserializer=compute__pb2.PromotionResponse.FromString,
                _registered_method=True)


class CoordinatorServicer(object):
    """Coordinator service (lightweight directory)
    """

    def RegisterNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAvailableNodes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateNodeStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterTaskReplica(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBackupForTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PromoteBackupToPrimary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoordinatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterNode': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterNode,
                    request_deserializer=compute__pb2.NodeRegistration.FromString,
                    response_serializer=compute__pb2.RegisterResponse.SerializeToString,
            ),
            'GetAvailableNodes': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAvailableNodes,
                    request_deserializer=compute__pb2.NodeRequest.FromString,
                    response_serializer=compute__pb2.NodeListResponse.SerializeToString,
            ),
            'UpdateNodeStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateNodeStatus,
                    request_deserializer=compute__pb2.NodeStatus.FromString,
                    response_serializer=compute__pb2.StatusResponse.SerializeToString,
            ),
            'RegisterTaskReplica': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterTaskReplica,
                    request_deserializer=compute__pb2.TaskReplicaRequest.FromString,
                    response_serializer=compute__pb2.TaskReplicaResponse.SerializeToString,
            ),
            'GetBackupForTask': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBackupForTask,
                    request_deserializer=compute__pb2.TaskBackupRequest.FromString,
                    response_serializer=compute__pb2.TaskBackupResponse.SerializeToString,
            ),
            'PromoteBackupToPrimary': grpc.unary_unary_rpc_method_handler(
                    servicer.PromoteBackupToPrimary,
                    request_deserializer=compute__pb2.PromotionRequest.FromString,
                    response_serializer=compute__pb2.PromotionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Coordinator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Coordinator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Coordinator(object):
    """Coordinator service (lightweight directory)
    """

    @staticmethod
    def RegisterNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Coordinator/RegisterNode',
            compute__pb2.NodeRegistration.SerializeToString,
            compute__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAvailableNodes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Coordinator/GetAvailableNodes',
            compute__pb2.NodeRequest.SerializeToString,
            compute__pb2.NodeListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateNodeStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Coordinator/UpdateNodeStatus',
            compute__pb2.NodeStatus.SerializeToString,
            compute__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterTaskReplica(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Coordinator/RegisterTaskReplica',
            compute__pb2.TaskReplicaRequest.SerializeToString,
            compute__pb2.TaskReplicaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBackupForTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Coordinator/GetBackupForTask',
            compute__pb2.TaskBackupRequest.SerializeToString,
            compute__pb2.TaskBackupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PromoteBackupToPrimary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Coordinator/PromoteBackupToPrimary',
            compute__pb2.PromotionRequest.SerializeToString,
            compute__pb2.PromotionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class NodeStub(object):
    """Node service (P2P with availability checking)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ComputeTask = channel.unary_unary(
                '/Node/ComputeTask',
                request_serializer=compute__pb2.TaskRequest.SerializeToString,
                response_deserializer=compute__pb2.TaskResult.FromString,
                _registered_method=True)
        self.Ping = channel.unary_unary(
                '/Node/Ping',
                request_serializer=compute__pb2.PingRequest.SerializeToString,
                response_deserializer=compute__pb2.PingResponse.FromString,
                _registered_method=True)
        self.CheckAvailability = channel.unary_unary(
                '/Node/CheckAvailability',
                request_serializer=compute__pb2.AvailabilityRequest.SerializeToString,
                response_deserializer=compute__pb2.AvailabilityResponse.FromString,
                _registered_method=True)
        self.ReserveForTask = channel.unary_unary(
                '/Node/ReserveForTask',
                request_serializer=compute__pb2.ReservationRequest.SerializeToString,
                response_deserializer=compute__pb2.ReservationResponse.FromString,
                _registered_method=True)


class NodeServicer(object):
    """Node service (P2P with availability checking)
    """

    def ComputeTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckAvailability(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReserveForTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NodeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ComputeTask': grpc.unary_unary_rpc_method_handler(
                    servicer.ComputeTask,
                    request_deserializer=compute__pb2.TaskRequest.FromString,
                    response_serializer=compute__pb2.TaskResult.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=compute__pb2.PingRequest.FromString,
                    response_serializer=compute__pb2.PingResponse.SerializeToString,
            ),
            'CheckAvailability': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckAvailability,
                    request_deserializer=compute__pb2.AvailabilityRequest.FromString,
                    response_serializer=compute__pb2.AvailabilityResponse.SerializeToString,
            ),
            'ReserveForTask': grpc.unary_unary_rpc_method_handler(
                    servicer.ReserveForTask,
                    request_deserializer=compute__pb2.ReservationRequest.FromString,
                    response_serializer=compute__pb2.ReservationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Node', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Node', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Node(object):
    """Node service (P2P with availability checking)
    """

    @staticmethod
    def ComputeTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Node/ComputeTask',
            compute__pb2.TaskRequest.SerializeToString,
            compute__pb2.TaskResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Node/Ping',
            compute__pb2.PingRequest.SerializeToString,
            compute__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckAvailability(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Node/CheckAvailability',
            compute__pb2.AvailabilityRequest.SerializeToString,
            compute__pb2.AvailabilityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReserveForTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Node/ReserveForTask',
            compute__pb2.ReservationRequest.SerializeToString,
            compute__pb2.ReservationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
